### ISSUE TITLE
Do not run Odigos UI if Odigos is not installed on the cluster

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#703]
When invoking the command `odigos ui` we should test if Odigos is installed on the Kubernetes cluster.
If Odigos is not installed we should abort the command (not running the UI) and show an error message.
We can detect if Odigos is installed via a similar logic to what is implemented in `odigos version`.

**Comment by Ritish134** [comment]
I would like to work on this issue can you assign it to me

**Comment by iamshreeram** [comment]
@edeNFed / @Ritish134 , I saw the PR; Instead of requiring a shell script for validation, can we utilize this [logic](https://github.com/keyval-dev/odigos/blob/main/cli/cmd/version.go#L45) to check if Odigos is installed in Kubernetes cluster? This would ensure uniformity throughout the component.

Any thoughts?

**Comment by edeNFed** [comment]
sounds good
